name: Maven Build and Checkstyle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Automatically runs on Node.js 20

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3  # Compatible with Node.js 20
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Cache Maven packages
      uses: actions/cache@v3  # Compatible with Node.js 20
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Install dependencies
      run: mvn install -DskipTests

    - name: Run Tests
      run: mvn test

    - name: Run Checkstyle
      run: mvn checkstyle:check

    - name: Upload Checkstyle Rep
